// Generated by CoffeeScript 1.7.1
import Ember from 'ember';
import Util from 'ember-cli-pagination/util';
var PageControllerMixin, c;

c = PageControllerMixin = Ember.Mixin.create({
  queryParams: ["page"],
  page: "1",
  pageChanged: (function() {
    var p;
    Util.log("page changed");
    p = parseInt(this.get('page'));
    return this.store.find('todo', {
      page: p,
      randInd: Math.random()
    }).then((function(_this) {
      return function(res) {
        var l;
        l = res.get('length');
        Util.log("setting content length " + l);
        return _this.set('content', res);
      };
    })(this));
  }).observes('page'),
  pageMetaBinding: "content.meta",
  totalPagesBinding: "pageMeta.total_pages"
});

export default c;
