// Generated by CoffeeScript 1.7.1
import Ember from 'ember';
import Util from 'ember-cli-pagination/util';
var DivideIntoPages, PagedArray;

DivideIntoPages = Ember.Object.extend({
  perPage: 10,
  objsForPage: function(page) {
    var e, perPage, s;
    perPage = this.get('perPage');
    s = (page - 1) * perPage;
    e = s + perPage - 1;
    return this.get('all').slice(s, +e + 1 || 9e9);
  },
  totalPages: function() {
    var allLength, perPage, res;
    allLength = parseFloat(this.get('all.length'));
    perPage = parseFloat(this.get('perPage'));
    res = (allLength + 1.99) / perPage;
    res = parseInt(res);
    if (allLength === 0) {
      res = 0;
    }
    Util.log("DivideIntoPages#totalPages, allLength " + allLength + ", perPage " + perPage + ", res " + res);
    return res;
  },
  range: function(page) {
    var e, perPage, s;
    perPage = this.get('perPage');
    s = (page - 1) * perPage;
    e = s + perPage - 1;
    return {
      start: s,
      end: e
    };
  }
});

PagedArray = Ember.ArrayProxy.extend({
  page: 1,
  perPage: 10,
  arrangedContent: (function() {
    var page, r;
    page = this.get('page');
    r = DivideIntoPages.create({
      perPage: this.get('perPage')
    }).range(page);
    return this.get('content').slice(r.start, r.end + 1);
  }).property("content.@each", "page", "perPage"),
  totalPages: (function() {
    return DivideIntoPages.create({
      perPage: this.get('perPage'),
      all: this.get('content')
    }).totalPages();
  }).property("content.@each", "perPage"),
  setPage: function(page) {
    Util.log("setPage " + page);
    return this.set('page', page);
  }
});

export default PagedArray;
