// Generated by CoffeeScript 1.7.1
import Ember from 'ember';
import Util from './util';
import DivideIntoPages from './divide-into-pages';

export default Ember.ArrayProxy.extend({
  page: 1,
  perPage: 10,

  divideObj: function() {
    return DivideIntoPages.create({
      perPage: this.get('perPage'),
      all: this.get('content')
    });
  },

  arrangedContent: function() {
    return this.divideObj().objsForPage(this.get('page'));
  }.property("content.@each", "page", "perPage"),

  totalPages: function() {
    return this.divideObj().totalPages();
  }.property("content.@each", "perPage"),
  
  setPage: function(page) {
    Util.log("setPage " + page);
    return this.set('page', page);
  }
});