// Generated by CoffeeScript 1.7.1
import Ember from 'ember';
var c;

c = Ember.Mixin.create({
  findPaged: function(name, params) {
    var page;
    page = parseInt(params.page || 1);
    return this.store.find(name, {
      page: page
    });
  }
});

export default c;
