// Generated by CoffeeScript 1.7.1
import Ember from 'ember';
var c;

c = Ember.Object.extend({
  responseHash: function() {
    var k, page, res;
    page = this.pageFromRequest(this.request);
    k = "" + this.name + "s";
    res = {};
    res[k] = this.objsForPage(page);
    res.meta = {
      total_pages: this.totalPages()
    };
    return res;
  },
  objsForPage: function(page) {
    var e, perPage, s;
    perPage = this.perPageFromRequest(this.request);
    s = (page - 1) * perPage;
    e = s + 1;
    return this.all.slice(s, +e + 1 || 9e9);
  },
  pageFromRequest: function(request) {
    var res;
    res = request.queryParams.page || 1;
    return parseInt(res);
  },
  perPageFromRequest: function(request) {
    var res;
    res = request.queryParams.per_page || 10;
    console.debug("perPage: " + res);
    console.debug(request.queryParams);
    return parseInt(res);
  },
  totalPages: function() {
    var perPage;
    perPage = this.perPageFromRequest(this.request);
    return parseInt((parseFloat(this.all.length) + parseFloat(perPage) - 0.01) / parseFloat(perPage));
  }
});

c.reopenClass({
  responseHash: function(request, all, name) {
    return this.create({
      request: request,
      all: all,
      name: name
    }).responseHash();
  }
});

export default c;
